CREATE TABLE tb_users (
 id UUID PRIMARY KEY NOT NULL,
 login VARCHAR(55) UNIQUE NOT NULL,
 password VARCHAR(55) NOT NULL,
 user_role VARCHAR(20) NOT NULL,
 created_on TIMESTAMP NOT NULL
);

CREATE TABLE tb_products (
id UUID PRIMARY KEY NOT NULL,
name VARCHAR(50) UNIQUE NOT NULL,
price DECIMAL NOT NULL,
created_on TIMESTAMP NOT NULL
);